######################################################################
# Automatically generated by qmake (2.01a) ?? ???? 1 22:56:59 2011
######################################################################

HEADERS += notifywidget.h dbus.h qclicklabel.h notifyarea.h
TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
QT += dbus
LIBS += -lX11
RESOURCES += images.qrc

# Input
SOURCES += main.cpp notifywidget.cpp dbus.cpp notifyarea.cpp message.cpp
